/**
 * AuditTest Vision — Popup Controller (Offline-First)
 *
 * Handles the extension popup UI:
 * - Start Audit triggers local WCAG analysis
 * - Shows accessibility score (0-100)
 * - Renders issue list with severity badges
 * - Copy fixes and Export as GitHub Issue
 */

interface AuditMessage {
  type: string;
  payload?: unknown;
}

interface AuditIssue {
  id: string;
  severity: 'critical' | 'major' | 'minor' | 'info';
  title: string;
  description: string;
  selector?: string;
  wcagCriterion?: string;
  fix?: string;
}

interface AuditReport {
  score: number;
  scoreLabel: string;
  totalIssues: number;
  criticalCount: number;
  majorCount: number;
  minorCount: number;
  issues: AuditIssue[];
  pageUrl: string;
  timestamp: string;
  durationMs: number;
}

// --- DOM Elements ---
const startBtn = document.getElementById('start-audit-btn') as HTMLButtonElement;
const statusEl = document.getElementById('status') as HTMLDivElement;
const resultsEl = document.getElementById('results') as HTMLDivElement;
const scoreEl = document.getElementById('score-value') as HTMLDivElement;
const scoreLabelEl = document.getElementById('score-label') as HTMLDivElement;
const criticalCountEl = document.getElementById('critical-count') as HTMLDivElement;
const majorCountEl = document.getElementById('major-count') as HTMLDivElement;
const minorCountEl = document.getElementById('minor-count') as HTMLDivElement;
const issueListEl = document.getElementById('issue-list') as HTMLDivElement;
const exportGithubBtn = document.getElementById('export-github-btn') as HTMLButtonElement;
const copyFixesBtn = document.getElementById('copy-fixes-btn') as HTMLButtonElement;

let currentReport: AuditReport | null = null;

// --- Event Handlers ---

startBtn.addEventListener('click', () => {
  startBtn.disabled = true;
  startBtn.textContent = 'Analizando...';
  setStatus('Extrayendo DOM y ejecutando reglas WCAG...');

  chrome.runtime.sendMessage({ type: 'START_AUDIT' }, (response: AuditMessage) => {
    if (response?.type === 'AUDIT_COMPLETE') {
      currentReport = response.payload as AuditReport;
      renderResults(currentReport);
    } else if (response?.type === 'AUDIT_ERROR') {
      setStatus(`Error: ${response.payload}`);
    }
    startBtn.disabled = false;
    startBtn.textContent = 'Start Audit';
  });
});

exportGithubBtn.addEventListener('click', () => {
  if (!currentReport) return;
  const payload = generateGithubIssue(currentReport);
  navigator.clipboard.writeText(payload).then(() => {
    exportGithubBtn.textContent = 'Copiado!';
    setTimeout(() => { exportGithubBtn.textContent = 'Export GitHub Issue'; }, 2000);
  });
});

copyFixesBtn.addEventListener('click', () => {
  if (!currentReport) return;
  const fixes = currentReport.issues
    .filter(i => i.fix)
    .map(i => `/* ${i.title} — ${i.selector || 'general'} */\n${i.fix}`)
    .join('\n\n');
  if (!fixes) return;
  navigator.clipboard.writeText(fixes).then(() => {
    copyFixesBtn.textContent = 'Copiado!';
    setTimeout(() => { copyFixesBtn.textContent = 'Copy All Fixes'; }, 2000);
  });
});

// --- Rendering ---

function setStatus(message: string) {
  statusEl.textContent = message;
  statusEl.classList.add('active');
}

function renderResults(report: AuditReport) {
  statusEl.classList.remove('active');
  resultsEl.classList.add('active');

  // Score
  const scoreColor = report.score >= 90 ? '#22c55e' : report.score >= 70 ? '#eab308' : report.score >= 50 ? '#f97316' : '#ef4444';
  scoreEl.textContent = String(report.score);
  scoreEl.style.color = scoreColor;
  scoreLabelEl.textContent = report.scoreLabel;
  scoreLabelEl.style.color = scoreColor;

  // Counts
  criticalCountEl.textContent = String(report.criticalCount);
  majorCountEl.textContent = String(report.majorCount);
  minorCountEl.textContent = String(report.minorCount);

  // Issue cards
  issueListEl.innerHTML = '';
  for (const issue of report.issues) {
    const card = document.createElement('div');
    card.className = `issue-item ${issue.severity}`;
    card.innerHTML = `
      <div class="title">[${issue.severity.toUpperCase()}] ${issue.title}</div>
      <div class="desc">${issue.description}</div>
      ${issue.fix ? `<div class="fix-line">${issue.fix}</div>` : ''}
    `;
    issueListEl.appendChild(card);
  }
}

// --- GitHub Issue Generator ---

function generateGithubIssue(report: AuditReport): string {
  const issueLines = report.issues.map(
    i => `- **[${i.severity.toUpperCase()}]** ${i.title}\n  ${i.description}${i.selector ? `\n  Selector: \`${i.selector}\`` : ''}${i.fix ? `\n  Fix: ${i.fix}` : ''}`
  ).join('\n');

  return `## AuditTest Vision Report

**Page:** ${report.pageUrl}
**Score:** ${report.score}/100 (${report.scoreLabel})
**Date:** ${report.timestamp}
**Duration:** ${report.durationMs}ms
**Issues:** ${report.totalIssues} (${report.criticalCount} critical, ${report.majorCount} major, ${report.minorCount} minor)

### Issues

${issueLines}

---
*Generated by AuditTest Vision v1.1.0*`;
}
